apiVersion: v1
kind: Secret
metadata:
    name: walla-db-secret
type: Opaque
stringData:
    mariadb-password: ENC[AES256_GCM,data:2xYFr44RUbK1,iv:TUO2zheOxndrg2MqPBuI55Ou74lIPq0qP6IhrZnMc4Y=,tag:ldV121674V/3If8HK4VEFg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:AMBstD0eHamF,iv:ApuIL8y0JAfZJ7tqhHKQB3ntjz7bV0RLFcYl8wI2odQ=,tag:sLz81rVtnjolcAckv7o6Dw==,type:str]
    username: ENC[AES256_GCM,data:rxYWsT6hUt0=,iv:Jb/QxIHCEyCWZpFDE1SR8toGmU88wWNtZvl16at3EUA=,tag:ySDZBpBx6mbVDpFXJS6HxA==,type:str]
    database: ENC[AES256_GCM,data:NZmyiSxRLdo=,iv:DbIXXRlk964bhljklaVSg2jdVBMbMWu7AvQ8sTRGbRk=,tag:CNfI/LlmCqVs9YdpzRkJEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvVVZodXdHbG5EeU4rZC9P
            clBNckRKaGRsQXRrQjNTa1hmbHhCNEhvdDF3CjJ1UmxBZEVobDZKL0pGcnFtV3ZZ
            NGhxR1VrcmNpamVTYXhKZitmV0VhdHcKLS0tIHpZSWYvdTkyUnV5MW1rQnBIY1NH
            TkRyZGpCQmh4Rmo1d2xTRldZbFJvRGcKwz0t2iKxtjkvlikpOOIqxg3BNQ0QEFGI
            DFkEoXU47AGaVgTL44sWpIeoveDsHmIxJ9um1msZv/sSp/DR84V32A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-26T12:35:55Z"
    mac: ENC[AES256_GCM,data:Mc4aVrLAXuZoDVQizoN+Z94MxxBGO0EFtnTrDkXcyUV1kAA99BwdzO2kj/lEu7qeVFynquY47wt1jzBlhJjq6VvpKos1pw4ry+yGZbCJ+V5VX1qTLXnKiCHEC4T6ndg3jYHUJ2uh+m0JDHlk/fAyAgdWgNpvawtoY9xBwi6D2Oo=,iv:SpLiSHEB5a8TBbXPm8Dg+85iMFJS6LP8LYyEi8RvBZ8=,tag:KNMmEYj8JKwa7aMQmC3oBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
