controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          repository: zadam/trilium
          tag: 0.53.2
        env:
          TRILIUM_DATA_DIR: /data
    initContainers:
        fix-permissions: 
          image: 
            repository: docker.io/busybox
            tag: latest
          command:
            - chown
            - -R
            - 1000:1000
            - /data




service:
  main:
    ports:
      http:
        port: 8080
ingress:
  main:
    enabled: true
    hosts:
      - host: notes.aksine.lcl
        paths:
          - path: /
            service:
              name: main
              port: http
    tls:
      - secretName: aksine-am-com-tls
        hosts:
          - notes.aksine.lcl
persistence:
  data:
    enabled: true
    type: persistentVolumeClaim
    existingClaim: notes-pvc
