apiVersion: v1
data:
    adminID: ENC[AES256_GCM,data:aPnG8CVw390=,iv:CeR77+ABSsZmEjZs5GPzuHBgWiPSgT5zHfnBJycawQU=,tag:RrC9aVdIF7te/sSsie/Ndg==,type:str]
    adminKey: ENC[AES256_GCM,data:E8AEjJ6ZDy34EVohz4rrIqwMagZ1jpWSVkSzl0OS+YbBj2Z881KCtcChuk00MUyQnCIg83e29nA=,iv:NoyD8cYmwvZ5URmN3advEy1hKrfana8mG1ZVAMfU5h4=,tag:wyVsFve2YaMZ6eRdPenH0Q==,type:str]
    userID: ENC[AES256_GCM,data:OXJlbWJbATY=,iv:tDHYbfrGdWZKleR50yP+4JIx+2qLw5qBtlAweHVr3fg=,tag:sao4djH0FIkRoPdPO08mCA==,type:str]
    userKey: ENC[AES256_GCM,data:lJJoTe9CV/sm6qqT+XBJ4+p0uFLwzb6GL7dRnOvAzGYDzeYYHCj4bmrLvxEwbvPg7mdTxtlh8mA=,iv:mAYSSccUmQAKVcADUvP5EtsBky1T/1hUlQFU263Hbrg=,tag:MgGVdtYjAqS4MH4SrEFpOA==,type:str]
kind: Secret
metadata:
    name: csi-cephfs-secret
    namespace: ceph-csi-cephfs
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYSGEzcGN4M1FoYWdsNzVv
            aTVGaThBRU1QSDNRbmg2VWRoQ3FXZ1I4V0E4CnlqL1dUNmtSU2orTEgyNFNVTUJq
            TTc2UlJuL1J0Q0swUFpoWVd5U1hPQ0EKLS0tIFZwUGRza3VCZG9IVGp3OS9XK2w4
            WUdMcmhSNW5iaHdXbXZwZGtldWMyZ0kKJApbU9M3ln41SNmOSrlwRTUyNEy2JWAy
            7/BiauNpxKOE5Hx9eAAv4+6iDfoOh02yutzH1PVgz7ErNulTUKKJPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-16T00:19:31Z"
    mac: ENC[AES256_GCM,data:8n8QZmOyT1ynEP/wP7q47ioJGoeWuyrZjubJ3gZINR+pKl1FWDFsuYbvytR9gXQ4lmoCrD4UtwZoabzPu5x2p5OUOajIIZWXzdLcc/6C2/LJcyQ7TKRERBJFzq6sNcbmnEkBwTPBsHfF6UVMFETphkR0ifFET7Y378Qp66xIC24=,iv:L/l9PMiiiFfyTYqw21D0AeeRvcoP5fdwokGzcm3mmTw=,tag:MxWYiaWnJnb+tM79iWkskA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
