primary: 
  # Enable persistence using Persistent Volume Claims
  persistence: 
    # If true, use a Persistent Volume Claim, If false, use emptyDir
    enabled: true
    # MySQL primary Pod security context
    existingClaim: ipam-pvc
auth:
  existingSecret: ipam-mysql-secret
image:

  tag: 5.7.40
