apiVersion: v1
kind: Secret
metadata:
    name: ipam-mysql-secret
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:3JLiDOh7zns=,iv:FIsCzJiYZYvDF7SzMyhP0EQtpLzQHdTCfsbTOVH3b0c=,tag:YItBtp59gXipoJZIprBFjA==,type:str]
    mysql-password: ENC[AES256_GCM,data:7CKeYDQA1f4=,iv:KCFbtWOeTP987qviC3drQbr+mCVZ/K0GHSYUKyRZukg=,tag:L8zn5EnR+qVhdkktjecAGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age10kvxklg29fhywc3en6fk3rkjr7ttsuvx8uvu2me0cntfvzpv8v3sx42pez
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJR1hkNEs1MUZoWGFDTXZp
            ejRBME4vZjAyOWJaUEdKTjZuZmV5UFJONUVRCno1ZmM5UEcrQVgzbGxpdlk0ZGVq
            UW8xc1BnTGlkQ3Q1V1pJR0J3bVhKU0kKLS0tIHF5RFN3TG1TVEpQMEIzSlEram1I
            eWtPTnhDZ2NWNlRUdjJuQldFMWhMdzQKHFPE6c6yZNyhMewbUa97E2dY7W1hH9xV
            MT/K1JTlpk8akRXkvyX3TWXnF11cUrWQHc8XgO9gZ51x48r0Z68xqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-23T03:29:55Z"
    mac: ENC[AES256_GCM,data:QYgxLhFrcY9e3DXm5tlFqSA64x0/gtksndAlRR0r0q2EtBu+fBVnf5XtevTja30Dt/qQo/djRNQ150pON2bX+cj59PJF0QbbgzCA0nfzn7HzpZX9Iir0/q/L+4MJ3EV9UuOVvjAhuSWOiKtn4lKFRMleKJ20yMNQJRpCOGLyEPg=,iv:b/jKCNF0q5sH9HvEkPi4AWWXhkXklVzqgrZ8IRmj0Iw=,tag:/h9KcY7PQpVwTeSEMu0U7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
